name: test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: Continuous Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17, 1.18]
      fail-fast: true
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Check out code
        uses: actions/checkout@v3
      - name: Cache Go modules
        uses: actions/cache@v3.0.4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build and test
        run: make test
      - name: Upload coverage report
        uses: actions/upload-artifact@master
        with:
          name: notation-coverage-report-${{ github.sha }}
          path: .cover/

